import Script from 'next/script'
import "./globals.css";



export const metadata = {
  title: "Blossoms And Bliss",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"className="h-screen ">
      <head>
        <link rel="icon" type="image/x-icon" href="/Logo.png"/>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Playwrite+NO:wght@100..400&display=swap"
          rel="stylesheet"
        />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossOrigin="anonymous"></script>
      </head>
      <body className="">
        {children}
        <script src='./handler.js'>
        </script>
      </body>
    </html>
  );
}
