import Script from 'next/script'
import "./globals.css";



export const metadata = {
  title: "Blossoms And Bliss",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"className="h-screen ">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Playwrite+NO:wght@100..400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="">
        {children}
        <script src='./handler.js'>
        </script>
      </body>
    </html>
  );
}
